stages:
  - update
  - build
  - test

update:
  stage: update
  script:
    - git pull origin main  # Update code from GitHub

build:
  stage: build
  script:
    - docker build -t my-app .

test:
  stage: test
  script:
    - docker volume create my_results_volume  # Create a results volume
    - docker volume create my_screenshots_volume  # Create a screenshots volume
    - docker run -v my_results_volume:/results -v my_screenshots_volume:/screenshots my-app pytest
    - docker cp my_results_volume:/results ./results  # Copy results from the volume to a local directory
    - docker cp my_screenshots_volume:/screenshots ./screenshots  # Copy screenshots from the volume to a local directory