stages:
  - update
  - test

update:
  stage: update
  script:
    - git pull origin main

test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.38.0-jammy
  script:
    - pip install -r requirements.txt  # Install project dependencies if needed
    - pytest  # Run pytest to execute your tests
